name: Main2DR
on:
  workflow_dispatch:
  push:
   branches: [ "main" ]
 # pull_request:
  #  branches: [ "main" ]
#  schedule:
#    - cron: "* */2 * * *" ##Running every 15min

permissions:
  id-token: write
  contents: write
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: myenv
    
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: Setup JFrog CLI for SAAS main
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli-main
        env:  
          JF_URL: "https://psblr.jfrog.io/"
        with:
          oidc-provider-name: destgithub
          custom-server-id: summain
          version: 2.72.4
      
      - name: Download file status.txt from repo
        run: |
          sudo echo "deb http://${{ steps.setup-cli-main.outputs.oidc-token }}:${{ steps.setup-cli-main.outputs.oidc-token }}@psblr.jfrog.io/artifactory/newdeb-virt bookworm main contrib" >> /etc/apt/sources.list
          sudo apt-get update
